name: CropXP
version: 1.1
author: Flintstqne
main: com.flintstqne.cropxp.CropXP
api-version: 1.16

commands:
  cropxp:
    description: CropXP command
    usage: /<command> [reload]
    aliases: [cxp]